services:

  airflow:

    image: apache/airflow:3.0.2

    container_name: airflow

    ports:
      - "8080:8080"

    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"

    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - .:/opt/airflow/project

    command: standalone
